version: "3.9"

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes: 
      - mysql:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/todoList
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
volumes:
  mysql:
    driver: local
